name: Learn English
favicon: null
layout_spectrum: 0.9727
typography_spectrum: 0.2934466458391398
title: Learn English
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000066'
    - '#cc0000'
    - '#7f7fb2'
    - '#db4f4f'
  brandStrength: 0.75
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
